### ISSUE TITLE
404 Error on Organisation Repo

### ISSUE THREAD

**Issue by SMNaik123** [sitek94/vite-deploy-demo#3]
Hi, 

Github pages works perfectly on repo created with personal github account. However, this gives 404 error on js & css files when used in a organization level repo. 

Any idea why this is happening?

**Comment by sitek94** [comment]
Are you using it as a repository specific `https://<organization>.github.io/<repository>` or main organization page `https://<organization>.github.io`? 

If the latter, then you would have to update the `base` in your vite config.
