### ISSUE TITLE
custom domain gets cleared after every deployment

### ISSUE THREAD

**Issue by minhtrinh06** [sitek94/vite-deploy-demo#4]
I'm not sure where in the deploy script is causing this.

**Comment by sitek94** [comment]
Can you share a link to your repo?

**Comment by minhtrinh06** [comment]
https://github.com/minhtrinh06/personal-site

**Comment by sitek94** [comment]
Thanks, I'll try to take a look at it later on in the evening.

**Comment by sitek94** [comment]
Hey, I've just checked your website and it seems to work fine:
https://minhtrinh.codes/

Anyway, I created a quick example for future reference if someone has similar problem:
https://github.com/sitek94/vite-deploy-demo-custom-domain

**Comment by sannidhyaroy** [comment]
This doesn't seem to fix it. The only way that I resolved it was manually adding a `CNAME` file containing the custom sub-domain into the `public` folder. Since, I'm not using an apex domain, I'm not sure, if this would work for an apex domain.
