### ISSUE TITLE
failed to load config

### ISSUE THREAD

**Issue by shoeslace911** [sitek94/vite-deploy-demo#6]
Hey mister, saw the tutorial and it helped me until adding the base url in vite.config.

I added the base URL in vite.config

![image](https://github.com/sitek94/vite-deploy-demo/assets/98511262/587b854a-2f6d-4a28-b9f4-d6b9559540d5)

but it gave me this error

![image](https://github.com/sitek94/vite-deploy-demo/assets/98511262/3345d90e-3daa-4b84-b77a-27003fc5579b)

I noticed in the error,  `/home/runner/work/the-black-bar/the-black-bar/vite.config.js` that `the-black-bar` is written twice making misleading GitHub actions.

Any help... would be a big one.
The link to the repo is <a href="https://github.com/shoeslace911/the-black-bar">HERE</a>

**Comment by shoeslace911** [comment]
![image](https://github.com/sitek94/vite-deploy-demo/assets/98511262/acd3260f-8bc2-438b-9915-b2b516a1aef0)

Wait... I think this is on my end. I'm having a problem running the app on my local server.

<strong>EDIT:</strong> Found a fix, I just downloaded @vite.js/plugin-react and then ran `npm run deploy`. Now it's fixed but the images are not loading. 

https://shoeslace911.github.io/the-black-bar/

**Comment by sitek94** [comment]
Hey check the PR 👆

**Comment by sitek94** [comment]
I actually had some ideas as well, so allowed myself to open some PRs. Hope you don't mind, cheers!
